export const RTSP_CERTIFICATION_MODE={
          NONE_CERTIFICATION:0
,DIGEST_CERTIFICATION:1
,DIGEST_OR_BASIC_CERTIFICATION:2

      };
export const RTSP_CERTIFICATION_MODEMap={
        [RTSP_CERTIFICATION_MODE.NONE_CERTIFICATION]:'NONE',[RTSP_CERTIFICATION_MODE.DIGEST_CERTIFICATION]:'DIGEST',[RTSP_CERTIFICATION_MODE.DIGEST_OR_BASIC_CERTIFICATION]:'DIGEST/BASIC'
      };
export const RTSP_CERTIFICATION_MODEList=[
        {label:'NONE',value:RTSP_CERTIFICATION_MODE.NONE_CERTIFICATION},{label:'DIGEST',value:RTSP_CERTIFICATION_MODE.DIGEST_CERTIFICATION},{label:'DIGEST/BASIC',value:RTSP_CERTIFICATION_MODE.DIGEST_OR_BASIC_CERTIFICATION}
      ];
export default {RTSP_CERTIFICATION_MODE,RTSP_CERTIFICATION_MODEMap,RTSP_CERTIFICATION_MODEList}